---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
spec:
  # schedule: "@daily"
  schedule: "0 */4 * * *" # every 6 hours at minute 0
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres16
