# https://github.com/benbusby/whoogle-search/blob/main/docker-compose.yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoogle
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/benbusby/whoogle-search
      tag: latest
    env:
      TZ: "${TIMEZONE}"
    persistence:
      # /config/:size=10M,uid=927,gid=927,mode=1700
      # /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      # /run/tor/:size=1M,uid=927,gid=927,mode=1700
      config:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 10Mi
        mountPath: /config/
      tor-1:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 15Mi
        mountPath: /var/lib/tor/
      tor-2:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 1Mi
        mountPath: /run/tor/
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: search
        hosts:
          - host: &host "search.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    # resources:
    #   requests:
    #     memory: 256mb
    #   limits:
    #     memory: 256mb
