---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 19.5.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    architecture: "standalone"
    auth:
      enabled: true
      existingSecret: redis-secret
      existingSecretPasswordKey: password
    master:
      resourcesPreset: "nano"
      persistence:
        enabled: false
    replica:
      resourcesPreset: "nano"
      persistence:
        enabled: false
    sentinel:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
