---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: babybuddy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/babybuddy
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: brettinternet
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://github.com/k8s-at-home/charts/tree/master/charts/incubator/babybuddy
  values:
    image:
      tag: arm64v8-latest
    controller:
      replicas: 1
      strategy: RollingUpdate
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: appdata
        subPath: babybuddy
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "baby"
        hosts:
          - host: &host "baby.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "babybuddy-tls"
