---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: babybuddy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/babybuddy
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: brettinternet
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: arm64v8-latest
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: appdata
        subPath: babybuddy
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: baby
          hajimari.io/instance: public
        hosts:
          - host: &host "baby.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["arm64"]
