---
session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: '{{ env "DOMAIN" }}_session'
      domain: '{{ env "DOMAIN" }}'
      authelia_url: 'https://auth.{{ env "DOMAIN" }}'
      default_redirection_url: 'https://{{ env "DOMAIN" }}'

access_control:
  default_policy: &policy two_factor
  networks:
    - name: internal
      networks: ['{{ env "CLUSTER_CIDR" }}', '{{ env "NODE_CIDR" }}', '{{ env "HOME_CIDR" }}']
  rules: []

identity_providers:
  oidc:
    jwks:
      - algorithm: RS256
        key: |-
          {{- env "OIDC_JWKS_KEY" | nindent 10 }}
    cors:
      endpoints: [authorization, token, revocation, introspection]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - client_name: Grafana
        client_id: grafana
        # docker run authelia/authelia:latest authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
        client_secret: '{{ env "GRAFANA_OAUTH_CLIENT_HASHED_SECRET"}}'
        public: false
        authorization_policy: *policy
        pre_configured_consent_duration: 1y
        scopes: [openid, profile, groups, email]
        redirect_uris: ['https://grafana.{{ env "DOMAIN" }}/login/generic_oauth']
        userinfo_signed_response_alg: none
