---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: $${DOMAIN}_session
      domain: $${DOMAIN}
      authelia_url: https://auth.$${DOMAIN}
      default_redirection_url: https://$${DOMAIN}

access_control:
  default_policy: &policy two_factor
  networks:
    - name: internal
      networks: ["$${CLUSTER_CIDR}", "$${NODE_CIDR}", "$${HOME_CIDR}"]
  rules: []

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - client_name: Grafana
        client_id: grafana
        client_secret: "$${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: *policy
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.$${DOMAIN}/login/generic_oauth"]
        userinfo_signed_response_alg: none
