---
- name: Ensure user groups exists
  ansible.builtin.group:
    name: sudo
    state: present

- name: Ensure group 'ssh' exists
  ansible.builtin.group:
    name: ssh
    state: present

- name: "Setup user groups, set user shell to {{ shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "{{ shell }}"
    groups:
      - wheel
      - sudo
      - ssh
    append: true
