---
- name: Clear MOTD
  become: true
  ansible.builtin.copy:
    content: ""
    dest: /etc/motd

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when:
    - timezone is defined

- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts to include inventory hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.1.1  {{ inventory_hostname }}"

- name: Enable forwarding and set other sysctl
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    reload: true
  with_dict: "{{ sysctl_config }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.bridge.bridge-nf-call-iptables: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.ipv4.conf.default.rp_filter: 0
      net.ipv4.conf.all.rp_filter: 0
      fs.inotify.max_user_watches: 524288
      fs.inotify.max_user_instances: 512

# https://serverfault.com/a/881518
# https://github.com/kubernetes/kubernetes/issues/53533
- name: Disable swap at runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Activating cgroup support
  become: true
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot

- name: Security
  ansible.builtin.include_tasks: security.yaml

- name: NFS
  ansible.builtin.include_tasks: nfs.yaml
  when: nfs_exports is defined and (nfs_exports | length > 0)
