---
- name: Clear MOTD
  ansible.builtin.copy:
    content: ""
    dest: /etc/motd

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when:
    - timezone is defined

- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts to include inventory hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.1.1  {{ inventory_hostname }}"

# https://wiki.debian.org/depmod
# May require reboot or `/usr/sbin/depmod -a` if fails
- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: 0644

- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Enable forwarding and set other sysctl
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    reload: true
  with_dict: "{{ sysctl_config }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.bridge.bridge-nf-call-iptables: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.ipv4.conf.default.rp_filter: 0
      net.ipv4.conf.all.rp_filter: 0
      fs.inotify.max_user_watches: 524288
      fs.inotify.max_user_instances: 512
      # https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
      net.core.rmem_max: 2500000

- name: Activating cgroup support
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot

- name: Swap
  ansible.builtin.include_tasks: swap.yaml

- name: Security
  ansible.builtin.include_tasks: security.yaml
#
# DNS
# https://hub.docker.com/r/adguard/adguardhome#resolved-daemon
# https://wiki.archlinux.org/title/systemd-resolved#DNS
# - name: Disable Ubuntu's caching DNS resolver on port 53
#   lineinfile:
#     dest: /etc/systemd/resolved.conf
#     line: "DNSStubListener=no"
#     regexp: "#?DNSStubListener=yes"
#     state: present

# - name: Create a symlink to resolv.conf
#   ansible.builtin.file:
#     src: /run/systemd/resolve/resolv.conf
#     dest: /etc/resolv.conf
#     owner: root
#     group: root
#     state: link
#   register: resolv_conf

# - name: restart systemd-resolved
#   service:
#     name: systemd-resolved
#     state: restarted
#   when: resolv_conf.changed
