# Security:
# - https://github.com/konstruktoid/ansible-role-hardening
# - https://github.com/dev-sec/ansible-collection-hardening
---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when:
    - timezone is defined

- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update network hosts
  ansible.builtin.copy:
    content: |
      127.0.0.1 localhost
      127.0.1.1 {{ inventory_hostname }}

      # The following lines are desirable for IPv6 capable hosts
      ::1     localhost ip6-localhost ip6-loopback
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
    dest: /etc/hosts
    mode: preserve

- name: Remove immutable flag from /etc/resolv.conf
  ansible.builtin.file:
    attributes: -i
    path: /etc/resolv.conf

- name: Remove /etc/resolv.conf
  ansible.builtin.file:
    attributes: -i
    path: /etc/resolv.conf
    state: absent

- name: Add custom /etc/resolv.conf
  ansible.builtin.copy:
    attributes: +i
    mode: "0644"
    dest: /etc/resolv.conf
    content: |
      search .
      nameserver {{ dns_address }}

- name: Install dependencies
  ansible.builtin.include_tasks: dependencies.yaml

- name: Setup system
  ansible.builtin.include_tasks: system.yaml

- name: Disable swap
  ansible.builtin.include_tasks: swapoff.yaml
