---
# Guide: https://ubuntu.com/server/docs/service-nfs
- name: Install
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs-kernel-server

- name: Ensure directories to export exist
  ansible.builtin.file:
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs is running.
  ansible.builtin.service:
    name: "{{ nfs_server_daemon }}"
    state: started
    enabled: true
