---
- name: Copy sudoers defaults
  become: true
  ansible.builtin.copy:
    src: sudoers-defaults
    dest: /etc/sudoers.d/defaults
    validate: "visudo -cf %s"
    mode: 0644

- name: Disable SSH password tunneling
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no

- name: Only allow SSH from current user
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers {{ ansible_user }}"
