---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: appdata-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: "${APPDATA_NFS_SERVER_CLUSTERIP}"
  share: /pvc
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
