---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: appdata-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: "${SECRET_NFS_APPDATA_SERVER}"
  share: "${APPDATA_DIR}"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
