---
title: Dashboard
theme: dark
color: zinc
headerStyle: boxedWidgets
layout:
  Calendar:
    style: column
    icon: mdi-calendar
  Media:
    style: column
    icon: mdi-play-circle
  Infrastructure:
    style: row
    columns: 3
    icon: mdi-server
  Storage:
    style: row
    columns: 2
    icon: mdi-desktop-tower
  Home:
    style: column
    icon: mdi-home-analytics
  Observability:
    style: column
    icon: mdi-chart-line
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
