kind: Secret
ansible_user: ENC[AES256_GCM,data:t/oOGVw=,iv:tUYHQ+hugNEQxk0z7153tYmmzPhzFH7Ctwv0Ud052io=,tag:Qfm4ypr7SjZKajDDGwrfYg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Jg/J1ALan4fnLhXK,iv:Q+/PKFuna3/1RDkYBSBEJTwtj607NcxMJB+trAoDlIw=,tag:7694n9o/5mOY1/FX3B0obg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaVhkS0tVNHkzVDliSGdO
            eSttdVYxUVNTOXhqZ3NtU0pteEtuREh4Vms0Cm5yb2tCYnViNFZ4VVBRY25xMktv
            VnROTWQ0SW1GZDcvSlBTYU8wRDE0b1UKLS0tIGdyaXJMLzNZOUVHYS9NT1NuZ1hT
            aUFpNnFWNGZKcmZCL3R2a1BTUGhZeFkKCE1+/+hEUMspyVpl/DJG63tAhPgBwUBi
            ZJzSFbCLw6AnL7WWXbLF8G0is83YeLUVQGplA3iid3/iDR/ggaELXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-27T16:36:31Z"
    mac: ENC[AES256_GCM,data:byuxjB2fDVoUyBhFFAKpii4pkgkB1uDP5oKxp+iBTNJBfmN5ndx4Thx53zgA1fNNnJ7WqgWjnxHF4Dnin8ArDXv7Ty7soyqBT2kxNQeCeiFhD9gnZuRx0Im8MUl5FHgEw3WPcTpqxJEyQ/qWU0NQP5UK8+AdkyRyX4G7jAahzlc=,iv:YYR7FNt9dkcOusljig/Sw9Wyv73ueRja/72KQwWFPW4=,tag:cKo/5rRYOFOQGyW7zNNRTw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.8.1
