---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lldap:
        replicas: 2
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            env:
              INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
              INIT_POSTGRES_DBNAME: lldap
              INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASSWORD}"
            envFrom: &fromSecret
              - secretRef:
                  name: lldap-secret
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: 2024-04-24-alpine
            env:
              TZ: "${TIMEZONE}"
              UID: "${SECURITY_CONTEXT_RUN_AS_USER}"
              GID: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
              LLDAP_LDAP_BASE_DN: "dc=home,dc=arpa"
              LLDAP_LDAP_USER_DN: admin
              LLDAP_HTTP_PORT: &port 80
              LLDAP_LDAP_PORT: &ldapPort 389
            envFrom: *fromSecret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        controller: lldap
        ports:
          http:
            port: *port
          ldap:
            port: *ldapPort
    ingress:
      app:
        className: internal
        hosts:
          - host: "ldap.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
