# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
type: Opaque
stringData:
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:tjf/IHc=,iv:bp8cStEaIB9ty7NXg8CDAy7KVGi3yziNDTNmYnPqpCs=,tag:e6IkbD2ncJGsL5/0ROmg9w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:fu0i8VF+w0mm34ZUFU6zcVh0JMvgGAyR3kq/855E2Ok=,iv:dNU7BlOrZ/P8d0Tguhjy+52wEmdPYAbDNf3tgKNqPyA=,tag:WZmMAQMUP2EVx5xG4XpWLw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:CAW/qMEfsKVyr+kXWrqXB42XYZRGeyOSprFfZpVnNH8OfaruLCj/NpCXc1VDeFNGSFcooeal0/S/x4z6lBHJmQkM6Pv+dnJL008wekNmFEf9gaMWZhtOQznbdQvxuatIALJb8VBqdNBW2Ny5+SFySzbZ5KMc7PHuYvA2+fXZr0Y=,iv:L5x4wkXudQIAMq/xDB8tv1PyF/Dum73mH6BG681tl0k=,tag:Yca4tlxhT9X+F0EfRADv1g==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:YIUwKwUy/M273ObtAF2WYCsl+0BMCsbifM1LJPOq9Yea3kV5Jgv6uadcbIKwLX2OZ29wdcEK6sUmHaFme4l+6mbNmDykJUfj0NSmoZWSrCxysc9vWWbk/lAu0eZGI2nqog1zGiQ1MEPmF4ekFeT7/z1qDssVV+97uX5qdmno97w=,iv:b5MFOX9RrdWJ8/pLznZCcn8szwSKVV/xWCgTITEBUeQ=,tag:ZpJVDGauMFR8a5oBzNwvrQ==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:ehCzYtXg1e55A7r7uuVcO3QeXdZclD8wAflwLb86uzAS+IrqhTiWOeRnizd8LLEUY0M5RsLmu/rYReSZ6zFYNm8f6nSzRfgBZUZWTatEuU1Jeb7X7Lz/1zWFgVoAEm3ZDhTsVuE=,iv:tB8fdrnmbXc+LNnA6bgQeuLtWPS7W1qt1e9YYZBcfAU=,tag:EgJmXh2of1Wd6e3EpqRTEw==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:lB8Ug5iT9qbVxrtGvEVbvCLj/ME=,iv:IfXFTzmBfYrut+jD4kh85SkQAbgTq97h1KawTRsnfvg=,tag:3N7tVmUe2pqalFfGWjRVdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmNZNDhCZldqNTBIajYw
            L3N0NFBqaE5xTGNORHpFc01IRVdpY0s3SzFNCnhjdHVNWVRCZ2QzMlN2MWEwUm56
            ZUNjWXpGNDlKTE1lOWRNNFQxa0I3K2MKLS0tIEF6aHUrSzhmcW1MdExPeUV3Z2o3
            OFV1djlrZVlEZHczc2xybjUrZjY2dlUKZTT68eHB2PwZywSMbiNdt8DCfIKBj8xU
            /tKZxkUL90K5JKyDCwfCfRm7Zw2zJ/wLM1t1vOBRZaB4e25CzZP03g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-03T00:06:38Z"
    mac: ENC[AES256_GCM,data:rHjPbQXy7yYwx5ehjABDsGDDR2PU19WjJy5JhSzq7fuup98CJPKg2s8eKuENLHfX/+g2IdHgOlvkaES++EOKsusGvHQIOHhEY6hWP0OuQ6fCMIyzToW7OK9Uuaq1tGr9OofTmzhrU7gVHz+peGyoLZORz1P5XYkp5zX4468aQz4=,iv:zT0jseCyNxB8MsxURDW1ilLngJEEZA3bqkKnYbR8PB4=,tag:Tzc0ZtDtY/EpjVT1gMPk4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
