apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia.yaml
  - bjw-s.yaml
  - brettinternet.yaml
  - cilium.yaml
  - descheduler.yaml
  - external-dns.yaml
  - grafana.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8s-gateway.yaml
  - kubereboot.yaml
  - kubernetes-dashboard.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
  - openebs.yaml
  - prometheus-community.yaml
  - stakater.yaml
