---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdata-monitoring
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: appdata-nfs-storage-monitoring
    volumeAttributes:
      server: "${APPDATA_NFS_SERVER_CLUSTERIP}"
      share: /

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  volumeName: appdata-monitoring
  storageClassName: ""
  resources:
    requests:
      storage: 60Gi
