---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: lscr.io/linuxserver/unifi-controller
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      PUID: "${SECURITY_CONTEXT_RUN_AS_USER}"
      PGID: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
    persistence:
      data:
        enabled: true
        mountPath: /config
        existingClaim: appdata
        subPath: unifi
    service:
      # Web admin
      main:
        ports:
          http:
            port: 8443
      # device communication
      device-comm:
        enabled: true
        ports:
          device-comm:
            enabled: true
            port: 8080
            protocol: TCP
            targetPort: 8080
      # STUN
      stun:
        enabled: true
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
            targetPort: 3478
      # AP discovery
      ap-discovery:
        enabled: true
        ports:
          ap-discovery:
            enabled: true
            port: 10001
            protocol: UDP
            targetPort: 10001
      # 'Make controller discoverable on L2 network' option
      l2-discovery:
        enabled: true
        ports:
          l2-discovery:
            enabled: true
            port: 1900
            protocol: UDP
            targetPort: 1900
      # mobile throughput test
      mobile-test:
        enabled: true
        ports:
          mobile-test:
            enabled: true
            port: 6789
            protocol: TCP
            targetPort: 6789
      # Remote syslog port
      syslog:
        enabled: true
        ports:
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
            targetPort: 5514
      # guest portal redirect ports
      guest-portal:
        enabled: false
        ports:
          guest-portal-https:
            enabled: false
            port: 8843
            protocol: TCP
            targetPort: 8843
          guest-portal-http:
            enabled: false
            port: 8880
            protocol: TCP
            targetPort: 8880
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hajimari.io/enable: "true"
          hajimari.io/icon: lan-pending
        hosts:
          - host: &host "unifi.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    nodeSelector:
      kubernetes.io/arch: amd64
