---
- hosts:
    - master
    - worker
  become: true
  vars_prompt:
    - name: nuke_confirmation
      prompt: |-
        Are you sure you want to nuke this cluster?
        Type HELL YES to proceed
      default: "n"
      private: false

  pre_tasks:
    - name: Check for confirmation
      ansible.builtin.fail:
        msg: Aborted nuking the cluster
      when: nuke_confirmation != 'HELL YES'

  tasks:
    - name: Uninstall k3s
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: uninstalled

    - name: Gather list of CNI files
      ansible.builtin.find:
        paths: /etc/cni/net.d
        patterns: "*"
        hidden: true
      register: directory_contents

    - name: Delete CNI files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ directory_contents.files }}"

    - name: Delete other directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/rook
