---
- hosts:
    - master
    - worker
  become: true
  tasks:
    - name: Get k3s service status
      ansible.builtin.systemd:
        name: k3s.service
      register: k3s_service_result

    - debug:
        var: k3s_service_result.status.ActiveState
