---
- hosts:
    - master
    - worker
  become: true
  roles:
    - kubernetes
    - kubecolor
  post_tasks:
    - name: Label node
      ansible.builtin.command:
        cmd: "kubectl label node {{ inventory_hostname }} {{ item }}"
      loop: "{{ node_labels }}"
      when:
        - node_labels is defined and node_labels | length > 0
    - name: Alias 'k' with kubectl
      become: false
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.profile"
        line: 'alias k="kubectl"'
    - name: Remove default StorageClass
      ansible.builtin.command: |
        kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

# Set default storageclass
# kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
