---
- name: Reboot
  hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting hosts
        reboot_timeout: 3600
