---
- name: Setup hosts
  hosts: kubernetes
  become: true
  pre_tasks:
    - name: Install packages
      ansible.builtin.package:
        state: latest
        name:
          - git
          - vim

  roles:
    - os
    - role: upgrade
      vars:
        allow_reboot: false
    - ssh
    - user
    - clamav
