# AdGuard does not support HA easily.
# TODO: Use https://github.com/0xERR0R/blocky or Unbound on OPNsense
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://brettinternet.com/charts/
      chart: ./charts/adguard
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: brettinternet
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: adguard
    env:
      TZ: "${TIMEZONE}"
    service:
      dns-tcp:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_DNS_ADDR}"
          metallb.universe.tf/allow-shared-ip: adguard-svc
      dns-udp:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_DNS_ADDR}"
          metallb.universe.tf/allow-shared-ip: adguard-svc
    persistence:
      config:
        enabled: true
        mountPath: /opt/adguardhome/conf
        existingClaim: appdata
        subPath: adguard
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-check"
        hosts:
          - host: &host adguard.${PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
