---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager
  - csi-driver-nfs
  - descheduler
  # - goldilocks
  - kube-vip
  - kured
  - kyverno
  - metrics-server
  - node-feature-discovery
  - reloader
  # - smarter-device-manager
  # - vpa
