# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:QuTtNq4rGuhmAzekSNklIOc95qYx0GPHFA7PwxWfHXH9VYqreQ==,iv:erMYqRJ30Ihm7QEpcZpxFT9kVWd+FQo+6uHpVTEelYA=,tag:vq/9zaN7YI/XZCVnaOjrVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZysvZUhybTZIMEdGZmRl
            NFNkZ21ONU9GTEY1emRVNThUZ1RlWXlVZlNrCkIrRk9TZHhUaGloenNMRXY3bjZj
            ckYySlhyanRTTVNVTmZvdlRyRkJGeEEKLS0tIHMvdVVUUW5RU3hUdGxRcFZOKzQv
            Vk5idzNIM1VFd3BSYlJLdHhXSlk5aEUKqOoqvQaQtkgPpH5dIlmAXrNg6Bouqb7t
            yoTgOizRwliyrVhd6mYA3o7XRrVxWEY0LUnuMAVUb98E6VA1Ka6Tnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T03:54:52Z"
    mac: ENC[AES256_GCM,data:ZSln4jCxjHOdInWBeYLXLBtXjRc9jEPP/SrimmoikKkmA+gZXyNjYBZZu6nTU8XkRtlGajIYIBsjDyoUMh7KXHpGneQkmYDZnQlngdVKDN9RVTzqUiAxC+j1ZqM8yFUbVth4yOddrfAtpsL1pIhmOW7C7chSC0i9UHxuyGK+iw0=,iv:8RCXdzaXZYHvVGhp1Sz32UmtWbHewKfukwKjyN7b6EA=,tag:hx8x+CMCfjpYVEdZAdfH0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
