# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:j0Q34Jpu0NZFK/J7nsak6eU/4WXYW2ztCc/WxYEPjWF/p3fSAQ==,iv:NWe9N+ZXBJ4jqIzvIY01B/zWae1wUFhoZJnFSINQjNU=,tag:Kf4++UgTUhA0bX/w85CWVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdlRBdGo5NjJ0cW9MMHJI
            Y2xWT3dBSHRyak95WE9FODA1S2FHR0pPWFJFCnFjNm1tODJwaXBMemkzQkpxYis4
            ZU9qTjAwMldLR0tHTHdpejdFdkNtWUUKLS0tIHBDNnhSQ2huemsvS1VaRWpKd1Vw
            MmFUL1EwRWxKb0w5VDdMR0RwVFg5UDAKlSuFTfnBlBzdtKieyZ0Onl4ErBweJLaM
            GEKrLz8CXXq74fty0js/6uvu3/o13RYUxXe5Lg+POOZWgk394yZ9NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T17:28:39Z"
    mac: ENC[AES256_GCM,data:ZP06obYJdUqC3xelgFejR+0XJu50UWo+oqqvM+JrQVeFd7bNoAjlh7W9e6dO4RK+uEp0HAUmcrx6vgkC8ds0ruWWsecZDMtoQ8VxR26rDDRkS/WtUI0NSrE5JxzrU2G0FNX1lvXhDxX2YRDzFN5fDynzmhyFaJkQp6sLOMkk3To=,iv:IDUr3Ebcd2cD44UxKFYqDJXP2lAQW7Q+UntIICypbsU=,tag:hnDY2CdPYsCt+blLVNtlAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
