# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:du/+QBefhDX+4OY0/mhJbRJCLCLwfUM=,iv:Wb1typ15R7NXA2W2Lsi6hRRUOmI9Ipsm5fJrrDbDPhI=,tag:JuKVxVJJRqI4agRlIhzUQg==,type:str]
    api-key: ENC[AES256_GCM,data:zku7rH7KFgTTIdnCRijW6UGR7mLEf7x1Vw7vFy40KKTi5Yx1+w==,iv:Vid3oCVbl5fcjYzAL0vmzBAecvlGkf7QZlbkfUSdiYI=,tag:G560cAvCzTU4a6Lfkda4sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpem45MDZSUkszYkxmQWZC
            aDFJZWY5eDFWb0dURmtKelBJK1pnVUpGdFRVCmNrU042eXhXT0FOVGxYZWZncFZy
            OFBscm5zZllKMnlQTUZ3Y1dUS1BuZVEKLS0tIEhFR0xQVmV6QWYzM3ZuVWhROHNr
            ZGU0cjd3VGZuR2xCNGVnd1F3Y25JVUUK67+/OJ1NV7yX9j6f1FbAQ9UHbzbj1YZc
            VRsueqh9eeISoJwGrsiGZe/iAbhtiTaNcOYeXDHCg2QyQjiIuAVTlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T07:38:54Z"
    mac: ENC[AES256_GCM,data:enhF5BnZKpy7kHTWF4rdTlJJ2BNcL2pssIBlmGw0pJ/eEEhUAXSe+XpbXdMt/Hm1aoOqGTQPjcRCERHcWdAaRcwngTlUZ7hpWgaXthOnC5Nvm2h8fbKFAMU5YoIW/aHNyHUkiHcJ2EE2ofiYXevQF6bpsPl8SN2cAJzqg5zJ7dk=,iv:fTZ73B8jmDmfpSoHZusIX0DvTnshv4MVdYlljcPXnGU=,tag:BxvOKXVpY8/wL/BuIiEipA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
