---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Denver
  METALLB_LB_RANGE: 10.1.2.100-10.1.2.110
  METALLB_K8S_GATEWAY_ADDR: 10.1.2.100
  METALLB_INGRESS_ADDR: 10.1.2.101
