---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Denver
  # Must be the same subnet as Node https://github.com/metallb/metallb/issues/433
  METALLB_LB_RANGE: 10.1.2.101-10.1.2.120
  METALLB_K8S_GATEWAY_ADDR: 10.1.2.101
  METALLB_INGRESS_ADDR: 10.1.2.102
  METALLB_INGRESS_INTERNAL_ADDR: 10.1.2.103
  METALLB_DNS_ADDR: 10.1.2.104
  APPDATA_NFS_SERVER_CLUSTERIP: 10.43.1.10
  APPDATA_DIR: /mnt/storage
