# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: grafana-secret
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:fH5dA8Ulzg==,iv:A5gpKCZbNDf5hUUg5lB7Epb5SmHVQxVcLW1+gn3aKS8=,tag:vsr0GUgY+ouUheCfYDLZzA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:3VYI7Yz81LjB+IVuwrlRZFwgGCxe5+LBUtmFDngfhlk=,iv:e8LiDcM7+Gj+geOkuQ1eIAIuqwuCRhpqYIDTNvgUcNQ=,tag:y4t3yCVSfj8LH81UBnO70Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVlZiSTM4SFROcGxPWHpS
            SDRaOUl6V0JobFVvVTJYUXlnejh5Wk9OcG5RCnhXdmM0Z3Fhd3RYS0Z4ZGJ3azdk
            Rm1xNHNIOUFzcFMwVGdoWlhueUpLeG8KLS0tIFU0T1lqK01rSEVzTW4xYXVmQWhZ
            MFZHQ2lQRDhrRU5iUXFMR0hneHNuQUUK6CZLaYuSorikaqv7QYEfdL7SWu8DJG8d
            +ORuTUzrOtQjHU6GtfQYhmXR+qzHUgkgQlVE7923C5jF/j+9IsWGKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-02T03:29:06Z"
    mac: ENC[AES256_GCM,data:fCW1ZTGq2aVcyW6zr6U//+8opOj3xp776OMB59HLnpknPo5ynBPgsH63OXJ7Kk4XfoylcK5EQPdmEZl3NQo1rMQPo3QMR/gW5IIKtUxDP6/oUDmbCB7qTR+tZoVc9FUETo+DCir+hHXf26Qt28uo8CqbKSmiSXCk8LYvn8+1cwo=,iv:Lr1Tsn37gh14Sjkh7uiys34vbJzSTX5I8kCqohbNQMM=,tag:EsPwE9Ih7ZlURwiUXnsNRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
