---
- Media:
    - YouTube:
        - icon: youtube.png
          href: https://youtube.com/feed/subscriptions
    - Spotify:
        - icon: spotify.png
          href: http://open.spotify.com
    - Plex:
        - icon: plex.png
          href: http://plex.${PUBLC_DOMAIN}
- Git:
    - GitHub:
        - icon: github.png
          href: https://github.com
