---
- Home:
    - HomeAssistant:
        href: https://home.${MEDIA_PUBLIC_DOMAIN}
        icon: home-assistant.png
        description: Home Assistant
        widget:
          type: homeassistant
          url: https://home.${MEDIA_PUBLIC_DOMAIN}
          key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
- Observability:
    - Healthchecks:
        href: https://healthchecks.${MEDIA_PUBLIC_DOMAIN}
        siteMonitor: https://healthchecks.${MEDIA_PUBLIC_DOMAIN}
        icon: healthchecks.png
        description: Job status
        widget:
          type: healthchecks
          url: https://healthchecks.${MEDIA_PUBLIC_DOMAIN}
          key: "{{HOMEPAGE_VAR_HEALTHCHECKS_TOKEN}}"
- Media:
    - Plex:
        href: https://plex.${MEDIA_PUBLIC_DOMAIN}
        siteMonitor: https://plex.${MEDIA_PUBLIC_DOMAIN}
        icon: plex.png
        description: Movies & TV
        widget:
          type: tautulli
          url: https://tautulli.${MEDIA_PRIVATE_DOMAIN}
          key: "{{HOMEPAGE_VAR_TAUTULLI_TOKEN}}"
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: true
    - Sonarr:
        href: https://sonarr.${MEDIA_PRIVATE_DOMAIN}
        siteMonitor: https://sonarr.${MEDIA_PRIVATE_DOMAIN}
        icon: sonarr.png
        description: TV
        widget:
          type: sonarr
          url: https://sonarr.${MEDIA_PRIVATE_DOMAIN}
          key: "{{HOMEPAGE_VAR_SONARR_TOKEN}}"
    - Radarr:
        href: https://radarr.${MEDIA_PRIVATE_DOMAIN}
        siteMonitor: https://radarr.${MEDIA_PRIVATE_DOMAIN}
        icon: radarr.png
        description: Movies
        widget:
          type: radarr
          url: https://radarr.${MEDIA_PRIVATE_DOMAIN}
          key: "{{HOMEPAGE_VAR_RADARR_TOKEN}}"
    - SABnzbd:
        href: https://nzb.${MEDIA_PRIVATE_DOMAIN}
        siteMonitor: https://nzb.${MEDIA_PRIVATE_DOMAIN}
        icon: sabnzbd.png
        description: Downloads
        widget:
          type: sabnzbd
          url: https://nzb.${MEDIA_PRIVATE_DOMAIN}
          key: "{{HOMEPAGE_VAR_SABNZBD_TOKEN}}"
- Calendar:
    - Agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 5
          integrations:
            - type: sonarr
              service_group: Media
              service_name: Sonarr
            - type: radarr
              service_group: Media
              service_name: Radarr
