---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdata
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: appdata-nfs-storage
    volumeAttributes:
      server: "10.43.1.10"
      share: /

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeName: appdata
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
