kind: Secret
ansible_user: ENC[AES256_GCM,data:yiY=,iv:Q3412rTo7su31KceRAMIQHXspqeHL82+6bJGcTFIWbk=,tag:GFUDnfP9nfcre/JkNetAsg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wfLTkQZIyXYsKWBF2Fji0Iw=,iv:WUbRuadITXTO/DApzXZUzzNMBWQdj7T3Y66NNUbhNxA=,tag:nbr3GtqXSpA0K396Y5Ag+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cDNqejgvYUd3R2xTb2Qy
            aVFIc05xQ1dQOU1qSktPaUU0R3lBZlFOVkF3CjZwSkJ2YVZ2djNkS0xUaVppU1Nl
            V2xZUEhHVUxxRysxZ1l0U0hXVG1wbVkKLS0tIE1nekJYbUVnMGVXcGcrbjNsZEFI
            YWh5WXhHZTdkTDVycnM1azkyUXczeEkKh86XvAEPj+JVXaN4ZeQOExGewTLUzHwk
            SJd4FTcp7YYNCpIJIkP9U/c2jrULfkfSZDHNHgQOKVLRNSaRrL+z9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T03:54:52Z"
    mac: ENC[AES256_GCM,data:xtlPh1UrgMSAetpO4eZKg0y18G5FEMhOmfJsLwkR64XEBnsnjrFK6RESZMJl4CRoUL0m5iDeY7bUbYcmVQvRcmyX2SmDryHcN3swxx+wIq8TJ+UHpU8HoAG+QN12LDTtNoFqdXkoZdqMb4q4Bs3MgG1KBRe6pi+vfZWSNvNBIpA=,iv:R1UE0kg1l7YNLOWSgdCi/r9hBDzQ0ceQNYTmhRZMG9E=,tag:mK3jnEokxPdYv4EBmQtg1g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
