kind: Secret
ansible_user: ENC[AES256_GCM,data:XG3Ua1U=,iv:3Ieyq6RR611PoUJXi8bCrYJNq5nJI4EViaZBRmoXtLw=,tag:MVuWhbjibG9k/eLgJn+VCw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:uMnwtrqtZvSueBu/,iv:KyGWMqlWjX11gtyuqiA9QN0dCNlyJVB+8V0w296Tbt0=,tag:wA/qOKtDdxVLUcf/X1yfNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQm9iTjJXTzlpMUJGcVlJ
            SGwzaXljWHk4dnc5NnNuN1l5SVdsNDAzcmpvClk2clJzTngxVnkzdmkzaFNkc3NH
            NTd3NWRrVjVtMWVwWXJ5dFJudjI1MU0KLS0tIElSVEsyN3RKUXVJSnR5cnNMdXhw
            b3plQ0huaVRlTGN4a2RGUTA4a0pQaVUKbOaQia14Xqa8sL6XC+orO3q+DH265Idx
            OLvW5r9uuGJwmJAv2dplLF3Xy+85pEmgeNNmriCcz4dk+w1BjKuYug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-27T16:36:31Z"
    mac: ENC[AES256_GCM,data:PA3pzqMqHGE8TOA6debzbV8u0WpmCnzL2ZC3qzdATrYbk0BWrUG9kSafT1uuuMUF1JSgt8ifBXhINUPoGQFiZ32JE8N4yAUWdfdTZZsMwnF3uaELOSY3ZhXjlJtJarevqvh5Qd82JA6E8wuP/gtBaP6RjLLJon1gfVgv/er9mMw=,iv:pT6+u70mOrKzGtDYsRAW//MpwTmePrRe8FvNlOBipmA=,tag:KBalWJ7+AHOVBnCY1Ti3cg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.8.1
