# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gatus-secret
stringData:
    NTFY_TOKEN: ""
    POSTGRES_USER: ENC[AES256_GCM,data:cPMJHq8=,iv:6cPNXaOQHGFMTXHyLP74rbgZXCTGf92s9aMO7dfDxzU=,tag:TTKVijos+0J5Ev6w8hdaSA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9nSbTJ8cTex53I7xH03opswizETtndkgYgitN8rc/Sc=,iv:vpTxq78dZwAL8BWyRAxoy+/MOkZfqaeDXbbGvonJxDo=,tag:4W2s9bj1TWJLNeaGb1Krnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSUxuaDRTN2cyQzRYRjJx
            UDNzYkJMRDZIWTNJRmNBcGlZeEZNaURtTW1ZCjNhb0twbHFIdDlLVUwvMXdiUk1O
            Ni9ZWFk0cXBiL05qcU94Tm9UMDVvN2MKLS0tIDFlcllzNTRtQ0xDNFBaelNMZUVZ
            OE1mRVljQlB1S2k4bytTeWZuUnZTdFkKJ8a+oku9jvH5gbUbvzgOjE8EJcHryOw6
            2XzNG5Zcx4BlLTsLdQ5wtccW596UKTsG/x2IdWJx+Xh1CMNi4PbulA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-04T05:25:03Z"
    mac: ENC[AES256_GCM,data:zmeiFOxQLCPJmUE3dHxSksoOOXyy3YyYOtsb7Dq7vHhZSNm7Qd/HMzlsXLzcVtVREPUiVMJYjTdQEnNY3ErFLCzVdwzzf3d0ElH7PgS8lyTFOm105V4N5vR9Gm+XmdKp3vTk3AA1I+dxgd9+sMes9jOvPssT+XfFcHuykkxytN4=,iv:S2EXD+N62pO7if9Uea+D9Cxq7thORyeqQtB3EnEz/as=,tag:N8UnOEZZc0g/R9nOeU+nlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
