---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/plexinc/pms-docker
      tag: plexpass
      pullPolicy: IfNotPresent
    # See https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/
    # NOTE: Plex preference options are camelCase and CASE SENSITIVE
    env:
      TZ: ${TIMEZONE}
      PLEX_UID: "${SECURITY_CONTEXT_RUN_AS_USER}"
      PLEX_GID: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
      # PLEX_CLAIM:
      #   valueFrom:
      #     secretKeyRef:
      #       name: plex
      #       key: PLEX_CLAIM
      # Remote access will look at `ADVERTISE_IP`, but because it's behind a proxy, it's likely that
      # the dashboard will say "Not available outside your network" even though it is... >:(
      ADVERTISE_IP: "https://plex.${PUBLIC_DOMAIN}"
      ALLOWED_NETWORKS: "10.1.1.0/24,10.1.2.0/24,10.2.0.0/24,10.42.0.0/16"
    # Ports: https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
    service:
      main:
        ports:
          http:
            port: 32400
      discovery:
        enabled: true
        # type: NodePort
        # externalTrafficPolicy: Local
        ports:
          # Plex DLNA Server
          # https://support.plex.tv/articles/200350536-dlna/
          dnla-tcp:
            enabled: true
            port: 32469
            protocol: TCP
            targetPort: 32469
          dnla-udp:
            enabled: true
            port: 1900
            protocol: UDP
            targetPort: 1900
          # GDM Network discovery
          # https://support.plex.tv/articles/200430283-network/
          gdm-1-udp:
            enabled: true
            port: 32410
            protocol: UDP
            targetPort: 32410
          gdm-2-udp:
            enabled: true
            port: 32412
            protocol: UDP
            targetPort: 32412
          gdm-3-udp:
            enabled: true
            port: 32413
            protocol: UDP
            targetPort: 32413
          gdm-4-udp:
            enabled: true
            port: 32414
            protocol: UDP
            targetPort: 32414
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /identity
            port: 32400
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: appdata
        mountPath: /config
        subPath: plex
      media:
        enabled: true
        existingClaim: media
        mountPath: /data/library
        subPath: library
      # https://support.plex.tv/articles/200250347-transcoder/
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
        # sizeLimit: 20Gi
        mountPath: /transcode
      tuner:
        enabled: true
        type: hostPath
        mountPath: /dev/dvb
        hostPath: /dev/dvb
      # Quick Sync https://github.com/plexinc/pms-docker#intel-quick-sync-hardware-transcoding-support
      dri:
        enabled: true
        type: hostPath
        mountPath: /dev/dri
        hostPath: /dev/dri
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: plex
        # be sure to access at `/web` instead of root `/`
        hosts:
          - host: &host plex.${PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    # resources:
    #   requests:
    #     # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #     # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #     gpu.intel.com/i915: 1
    #     cpu: 200m
    #     memory: 256Mi
    #   limits:
    #     # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #     # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #     gpu.intel.com/i915: 1
    #     memory: 4096Mi
    nodeSelector:
      feature.node.kubernetes.io/custom-tuner: "true"
