# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: networking
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:QJ7bBrAD9Q==,iv:5IC4hv3BBgUxmsdzqX5r38YyAGPQApsjRzrWsDt1G5I=,tag:xJQPUDb9hgu9s+A8afcFDg==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:D0Eo552W5GrD,iv:ZCRq06I2zhJbvr4a72yKTyDfC14O1UdiLW92ZN9jmJc=,tag:C79ik7sVPldwKLOlTsRDfg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:HNaTuLLG44GqSvQJ4OqYIsexPNjzgS4bNJddgbp5lkbWZEl3lQgoNX+WHJ4=,iv:9+cWb17LsaLGw/kDJ41BNNLgAdUMxKS6hEo8EAIb24s=,tag:rFed+J2uS837nDZqWK7BFw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:rh9F63Sh3Vx5xHmsF9b5,iv:b4e3hK7PJwmxw4ciC/7zAd0KuvNHdBhGzFsxRC8Msjs=,tag:WGJIn6DKcedSQVlrWLbUVQ==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:xwG/RoF7tEyf,iv:WAVDK34Lti6QSHBmznoWxBzohMD4tYrcw8bYFaZ3CYc=,tag:dI6auEYZOHX20hvFhVNzeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ3BIMUl5QUpITXBBaFZV
            QzB4eDAyZnVkb1VpaENDUWMxNDByc01rWFV3CmkzaExXTUZIRlVURkdWcmp3dFlo
            ZWNtRDRPakRsVEZXVDZ1cG85VVBXS28KLS0tIFI5b3FlYVlwWnBpVVU2WDAwOTNO
            UUJ4Wmc1VUhZUjBaaGZoMkFDZmxRMjQKTtn9Zv03ss9c8pbwRbMSvoN2WnUDSPTE
            WIyazYoGf4D3E4yaAKnV9IiRRnzEWVrfULrSu5/l4svrrP/NM/rK/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-17T06:24:47Z"
    mac: ENC[AES256_GCM,data:rDO0PoH5yY8ywF0duho8oR9BkNGFp4BC1VJRt105/5+pjwr5zssCa91vOTgDtvgN5XkQD+lp2bVxD2o6HRfhsOiNZ2om7wSiEVhJ/JgHbcgUWll4jLnKxyIwle+4QkGqPSn8/XjXWPhiu+Tn1tgHrKYq1pR4whLwg5DQcRSgg5A=,iv:Mhzx61QI8hch3fI/V9A3WBu9u5pCHy8WZVuOIUBxU+s=,tag:WzfLr1JFs5QUIsctbxf8Tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
