---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: ntfy
        url: http://ntfy.comms.svc.cluster.local
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
