---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ntfy:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        # initContainers:
        #   init-dir:
        #     image:
        #       repository: docker.io/library/busybox
        #       tag: latest
        #     command: [sh, -c, mkdir -p /data/attachments]
        #   init-ls:
        #     dependsOn: init-dir
        #     image:
        #       repository: docker.io/library/bash
        #       tag: latest
        #     command: [ls, -l, /data]
        containers:
          app:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.10.0
            args: [serve]
            env:
              TZ: "${TIMEZONE}"
              BUMP: 1
              # https://docs.ntfy.sh/config/#config-options
              NTFY_LOG_LEVEL: DEBUG
              NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
              NTFY_BEHIND_PROXY: true
              NTFY_BASE_URL: "https://ntfy.${PUBLIC_DOMAIN}"
              NTFY_SMTP_SENDER_ADDR: maddy.comms.svc.cluster.local:25
              NTFY_SMTP_SENDER_FROM: "ntfy <${SMTP_FROM}>"
              NTFY_AUTH_DEFAULT_ACCESS: read-only
              NTFY_AUTH_FILE: /data/auth.db
              NTFY_CACHE_FILE: /data/cache.db
              # NTFY_ATTACHMENT_CACHE_DIR: /data/attachments
              NTFY_ENABLE_LOGIN: true
              NTFY_ENABLE_SIGNUP: true
    service:
      app:
        controller: ntfy
        ports:
          http:
            port: 80
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${PUBLIC_DOMAIN}"
        hosts:
          - host: "ntfy.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistance:
      data:
        existingClaim: ntfy
        globalMounts:
          - path: /data
        # advancedMounts:
        #   ntfy:
        #     init-dir:
        #       - path: /var/lib
        #     init-ls:
        #       - path: /var/lib
        #     app:
        #       - path: /var/lib/ntfy
