---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ntfy:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: latest
            env:
              TZ: "${TIMEZONE}"
              # https://docs.ntfy.sh/config/#config-options
              NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
              NTFY_BEHIND_PROXY: true
              NTFY_BASE_URL: "https://ntfy.${PUBLIC_DOMAIN}"
              NTFY_SMTP_SENDER_ADDR: maddy.comms.svc.cluster.local:25
              NTFY_SMTP_SENDER_FROM: "${SMTP_USER}"
              NTFY_AUTH_DEFAULT_ACCESS: read-only
              # NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
              NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
              NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
              NTFY_ENABLE_LOGIN: true
              NTFY_ENABLE_SIGNUP: true
            args: [serve]
    service:
      app:
        controller: ntfy
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${PUBLIC_DOMAIN}"
        hosts:
          - host: "ntfy.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistance:
      cache:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 5Gi
