# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: ntfy
    namespace: comms
stringData:
    auth: ENC[AES256_GCM,data:ZP2fhxUwh7Fvi3Dmhtkop8TbIp1ryNueW73OJqpaSlgEI8MdpS/vLf8YS/dBr7SeDTjWpFvYxgYVAD1Tt+aYArpWJNEakQ==,iv:4Xjc3f0naxZPNpXakxXpcf6Tt6V6dBIJB8NJuS+AAZ0=,tag:4ZXflsmoGEKCQ71JMt3cyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd01xYUE1Q3B1N29MNFBC
            MmVzTmYrL1Jmc1lBeDQ3QkEzcFA4QUlJOWlVCnpnSFdaTG1vOUNidW1XWmRhaWlS
            SXo1cU5za3gzeThUbm5DbXNTeklIN2cKLS0tIG9yeFRMc05IZUFiU0tQaG83c1JQ
            c0paMkpLenYrNlViMGptVTNZdVg4R0kK8jMUb0oLWxhZ5/Cd8bHjFJk/OnpYzyGO
            x2QnTjB6wxA09U+G9iIrrkDlkKZ+a4RM5qO5f57IfWRToJXJJ4i6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T16:53:44Z"
    mac: ENC[AES256_GCM,data:1OPdL2YrQSBdaFZISVQ6E1h1COQh5qdSsoE8TymFFH/dNHZI5Hv9Ieh9HwnPaE/eJAOXsRDo3LOloh78WpEN/fFJ+XJm1jOqGD9Epgj+ZrDcTISrqt/WQvCVkmp3v6mx+qS+KNnZwxdOZjmXUi1M2FLIodWQSCNtfJdaQyJsb8c=,iv:pn4FwVkecsGxtvHsNrP8vMfwtWm5xXHY1ovNyVbwXOA=,tag:RW9bxk9a/I9v6dqRkyHC0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
