---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: busybox
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      dnsConfig:
        options:
          - name: ndots
            value: "5"
    controllers:
      busybox:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/library/busybox
              tag: latest
            command:
              - sleep
              - "3600"
    service:
      app:
        enabled: false
    ## healthcheck?
    # command:
    #   - sh
    #   - -c
    #   # https://stackoverflow.com/a/19139134
    #   # https://busybox.net/downloads/BusyBox.html#nc
    #   - while true ; do echo -e 'HTTP/1.1 200 OK\n\n $(date)' | nc -l -p 3000; done
