---
- name: Check if cluster is installed
  check_mode: false
  ansible.builtin.stat:
    path: /etc/rancher/k3s/config.yaml
  register: k3s_installed

- name: Upgrade and reboot if first run
  ansible.builtin.include_role:
    name: upgrade
  vars:
    # Reboot only if initial setup
    allow_reboot: "{{ not k3s_installed.stat.exists }}"

- name: Prevent downgrades
  when: k3s_installed.stat.exists
  ansible.builtin.include_tasks: version-check.yaml

- name: Install k3s
  ansible.builtin.include_tasks: k3s.yaml

- name: Cilium
  when: k3s_primary_control_node
  ansible.builtin.include_tasks: cilium.yaml

- name: Clean
  when: k3s_primary_control_node
  ansible.builtin.include_tasks: clean.yaml
