---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # https://github.com/longhorn/longhorn/blob/master/chart/README.md
  values:
    csi:
      attacherReplicaCount: &replicas 1
      provisionerReplicaCount: *replicas
      resizerReplicaCount: *replicas
      snapshotterReplicaCount: *replicas
    defaultSettings:
      defaultReplicaCount: *replicas
      defaultDataPath: /var/lib/longhorn
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: true
      replicaAutoBalance: true
      storageMinimalAvailablePercentage: 1
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      guaranteedInstanceManagerCPU: 20
      orphanAutoDeletion: true
      # backupTarget: s3://longhorn@ca-west-1/
      # backupTargetCredentialSecret: longhorn-secret
    persistence:
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    longhornUI:
      replicas: *replicas
    ingress:
      enabled: true
      ingressClassName: internal
      host: "longhorn.${PUBLIC_DOMAIN}"
      tls: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Observability
        gethomepage.dev/name: Longhorn
        gethomepage.dev/icon: mdi-zip-disk
    metrics:
      serviceMonitor:
        enabled: true
