# https://github.com/PrivateBin/PrivateBin
# https://github.com/PrivateBin/docker-nginx-fpm-alpine
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: privatebin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      # https://hub.docker.com/r/privatebin/nginx-fpm-alpine/
      repository: docker.io/privatebin/nginx-fpm-alpine
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      PHP_TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8080
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
    persistence:
      config:
        enabled: true
        existingClaim: appdata
        subPath:
          - path: privatebin/data
            mountPath: /srv/data
          - path: privatebin/conf.php
            mountPath: /srv/cfg/conf.php
            readOnly: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: content-paste
        hosts:
          - host: &host "paste.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
