---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dokuwiki
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/dokuwiki
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: brettinternet
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: lscr.io/linuxserver/dokuwiki
      tag: arm64v8-latest
    env:
      TZ: "${TIMEZONE}"
    persistence:
      data:
        enabled: true
        mountPath: /config
        existingClaim: appdata
        subPath: dokuwiki
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: file-document-multiple
          hajimari.io/instance: public
        hosts:
          - host: &host "wiki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: dokuwiki-tls
