---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app iventoy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      iventoy:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/ziggyds/iventoy
              tag: latest
            env:
              TZ: ${TIMEZONE}
              AUTO_START_PXE: true
            securityContext:
              privileged: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 512M
    # https://www.iventoy.com/en/doc_portnum.html
    service:
      app:
        controller: *app
        ports:
          http:
            port: 26000
      iventoy:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${LB_IVENTOY_ADDR}"
        ports:
          dhcp:
            port: 67
            protocol: UDP
          tftp:
            port: 69
            protocol: UDP
          pxe:
            port: 16000
            protocol: TCP
          nbd:
            port: 10809
            protocol: TCP
    ingress:
      app:
        className: internal
        hosts:
          - host: "iventoy.${PRIVATE_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      isos:
        existingClaim: *app
        globalMounts:
          - path: /app/iso
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/data
