---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # official Authelia chart is still in beta
      # https://github.com/authelia/chartrepo
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: lldap
      namespace: default
    - name: authelia-postgres
      namespace: default
    - name: authelia-redis
      namespace: default
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.36.6
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: 9091
          metrics:
            enabled: false
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
        hosts:
          - host: &host "auth.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: authelia-tls
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
        readOnly: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    # resources:
    #   requests:
    #     cpu: 5m
    #     memory: 10Mi
    #   limits:
    #     memory: 100Mi

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgres
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  # https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  # https://artifacthub.io/packages/helm/bitnami/postgresql
  values:
    fullnameOverride: authelia-postgres
    image:
      # Use image with ARM64 support
      # https://hub.docker.com/_/postgres
      repository: library/postgres
      tag: 14
    auth:
      enablePostgresUser: false
      username: authelia
      password: "${AUTHELIA_POSTGRES_PASSWORD}"
      database: authelia
    postgresqlDataDir: /var/lib/postgresql/data
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      persistence:
        enabled: true
        mountPath: /var/lib/postgresql/data
        existingClaim: appdata
        subPath: authelia_db

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 17.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://artifacthub.io/packages/helm/bitnami/redis
  values:
    image:
      repository: library/redis
      tag: latest
    auth:
      enabled: false
      sentinel: false
      password: "${AUTHELIA_REDIS_PASSWORD}"
    sentinel:
      enabled: false
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    replica:
      replicaCount: 1
    master:
      persistence:
        enabled: true
        path: /data
        existingClaim: appdata
        subPath: authelia_redis
