---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - backup
  - default
  - flux-system
  # - games
  - kube-system
  - media
  # - monitoring
  - networking
  - system-upgrade
  # - trivy
