---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app miniflux
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: miniflux-postgres
      namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/miniflux/miniflux
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      CREATE_ADMIN: "1"
      RUN_MIGRATIONS: "1"
      LOG_DATE_TIME: "1"
      # https://miniflux.app/docs/howto.html#oauth2
      OAUTH2_PROVIDER: oidc
      OAUTH2_CLIENT_ID: miniflux
      # openssl rand -hex 16
      OAUTH2_CLIENT_SECRET: "${MINIFLUX_OAUTH_CLIENT_SECRET}"
      # OAUTH2_USER_CREATION: "1"
      OAUTH2_REDIRECT_URL: "https://rss.${PUBLIC_DOMAIN}/oauth2/oidc/callback"
      OAUTH2_OIDC_DISCOVERY_ENDPOINT: "https://auth.${PUBLIC_DOMAIN}/.well-known/openid-configuration"
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 8080
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: rss
          hajimari.io/instance: public
        hosts:
          - host: &host "rss.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    # resources:
    #   requests:
    #     cpu: 50m
    #     memory: 64Mi
    #   limits:
    #     memory: 96Mi

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux-postgres
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  # https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  # https://artifacthub.io/packages/helm/bitnami/postgresql
  values:
    fullnameOverride: miniflux-postgres
    image:
      # Use image with ARM64 support
      # https://hub.docker.com/_/postgres
      repository: library/postgres
      tag: 14
    auth:
      enablePostgresUser: false
      username: miniflux
      database: miniflux
      existingSecret: miniflux
      secretKeys:
        userPasswordKey: POSTGRES_PASSWORD
    postgresqlDataDir: /var/lib/postgresql/data
    primary:
      podSecurityContext:
        enabled: false
        # fsGroup: 1000
      containerSecurityContext:
        enabled: false
        # runAsUser: 1000
      persistence:
        enabled: true
        mountPath: /var/lib/postgresql/data
        existingClaim: appdata
        subPath: miniflux_db
