---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://brettinternet.com/charts
      chart: ./charts/miniflux
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: brettinternet
        namespace: flux-system
      interval: 15m
  dependsOn:
    - name: miniflux-postgres
      namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "${TIMEZONE}"
      CREATE_ADMIN: "1"
      ADMIN_PASSWORD: "${MINIFLUX_ADMIN_PASSWORD}"
      DATABASE_URL: "postgres://miniflux:${MINIFLUX_POSTGRES_PASSWORD}@miniflux-postgres.default.svc.cluster.local/miniflux?sslmode=disable"
      RUN_MIGRATIONS: "1"
      LOG_DATE_TIME: "1"
      OAUTH2_CLIENT_ID: miniflux
      # openssl rand -hex 16
      OAUTH2_CLIENT_SECRET: "${MINIFLUX_OAUTH_CLIENT_SECRET}"
      OAUTH2_USER_CREATION: "1"
      OAUTH2_OIDC_DISCOVERY_ENDPOINT: "https://auth.${PUBLIC_DOMAIN}"
      OAUTH2_PROVIDER: oidc
      OAUTH2_REDIRECT_URL: "https://miniflux.${PUBLIC_DOMAIN}/oauth2/oidc/callback"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: rss
          hajimari.io/instance: public
        hosts:
          - host: &host "rss.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: miniflux-tls
    # resources:
    #   requests:
    #     cpu: 50m
    #     memory: 64Mi
    #   limits:
    #     memory: 96Mi

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux-postgres
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  # https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  # https://artifacthub.io/packages/helm/bitnami/postgresql
  values:
    fullnameOverride: miniflux-postgres
    image:
      # Use image with ARM64 support
      # https://hub.docker.com/_/postgres
      repository: library/postgres
      tag: 14
    auth:
      enablePostgresUser: false
      username: miniflux
      password: "${MINIFLUX_POSTGRES_PASSWORD}"
      database: miniflux
    postgresqlDataDir: /var/lib/postgresql/data
    primary:
      podSecurityContext:
        enabled: false
        # fsGroup: 1000
      containerSecurityContext:
        enabled: false
        # runAsUser: 1000
      persistence:
        enabled: true
        mountPath: /var/lib/postgresql/data
        existingClaim: appdata
        subPath: miniflux_db
