# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:zC5oOL7Z/HnCiBARhSjXwb0=,iv:XrE7dnl5osta7aZUKVt8Ax8ix5BL+yZ3rO8OSoRnnM8=,tag:81fxToq3/TqiVNTn1mnH6w==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/EC3G5kYMDjqggHp9ZkXH+ofmC7Hm8Q=,iv:V2UqdDZsi4qqL4q/+5kQHfjuD4BffczWEKoKT3AKK3Q=,tag:zgSg8OEDYq/AMc3lD/47jA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5ox/Byqc0lIbFKvO2keUXKi1KL0aEo+1bAUMq4wLbJo17Y+d,iv:1lI20TAs0BGqAQWrTQWD67LK29gMBqManzBAuq6+vfI=,tag:a5wjRYNwxGRytvjqgzvJkQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:boTe8GD3ykMJcv8mR/v1WvwG0oQPEv4=,iv:XPekuqRBlOm/JIY0peOURWMQm6KXfhKYaLT/i3bYjPY=,tag:o4TEG4iQWYR9cCIC95s/Ow==,type:str]
    NOTIFY_EMAIL: ENC[AES256_GCM,data:GqDxBZm9WBScfQTffDOye9mJ/1I=,iv:OzMGKSQJXAd0fiBnfO9iMvurxXonon683lGw98WUZoY=,tag:OFNWNRRPDOfKwQzTV2Uopg==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Ohj3TMH3FZRAcN8oLKrWRdTTSqo9ewwaIBCWoAvv3VA=,iv:/ZbcdDjS5We3oF/I96tB0sNWhN4GtYE4dgm8IZi2xxg=,tag:xVaj7BpXHTGSTq9LGNDN8w==,type:str]
    THANOS_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:D7P2hl7sjt7Ytt5YexDFkTrbIDWMiWWjvXxeFxeb1qE=,iv:OG8fVnjiimijWb4jsBbkRVZgYZlLGrxF1sIq73QB/Cw=,tag:f8U0elf+4YUhxRRlbUnC0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RjFYbS85VXcwdndndHNP
            U3IwSGV4Z3BPMjM3VnF0Z3dpYWU4NUQ1UVRjClRvQnAvV3dBMG9SNkhMWWhZMC9S
            QU5XbHFkL1h4QVpacXJrL0NuSkNrQTQKLS0tIHRXcGUyWk5tbmt4blNXdEdsREpr
            ZHdTRW9rdTR5NWUvN0hwQVJWNE5ZUHMKrrwIoC2u8ifnbSKceEvXNX1ktlAggMmb
            QYrfm8TawcSEqhHfSlN9VcUtusT/jo6dm5Pb2zoHB8NRDOsz/QcyWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-29T05:46:14Z"
    mac: ENC[AES256_GCM,data:6gnXkVqrX4/tb+EP48rZQqETDekiZaXbzgusExF+Vm+gwcVgoJI6GuavLpo4Q2FJdQk8D1HFBYaSlZE9AxgrcIfnHPVKq6bA3Ymet2QqiTp6kzl78VO9prTW+Gp0pUDFkL4G6EHrtQbmYA71glmj8cKT83pCSP2zfuArbjIUs18=,iv:0R+ZQ6QY38BPgtQamEyQSbYC2g88jchiuvSQZZw2uas=,tag:+RkXWsM3p7MpUGWo06pVqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
