# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:tv1PD6LtvZN+rEhaWtwgYXY=,iv:PYSBQZ++09wnnmvRe1xHPHz+MAIFIId1xQ6qXOSJKhQ=,tag:i8WURJSz7vALhVmsY5JvNA==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:etJVTHsCZz78/USybhIlXbbWk0iNA88=,iv:B9W7ovvKl+iO+iwtJ4VtlH5k95qMmFy893IndNdxW0I=,tag:Qk7e9zm7ZOcOpkjaOivwIw==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TMbAOXAlGz23bu3ZN/sKsS3ckwVJx7lFcuWVU8IPko6q2wVz,iv:ZkkZYTl/d+lxgs3Em1jHIZv8m5otgfbRbIJUc+7yzEw=,tag:Vq2beRnm7fT4mZA/bTa3vg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:qqAqOT5q+0StoDdF31vc6UsuYZ+lQQbDMLgKpA==,iv:xmIHKKQ3CQqoYnrQDRzk8EtsQ8doCUAh60c/mVozmKI=,tag:Ff1rKBRUKa//BdU0pX6g6A==,type:str]
    NOTIFY_EMAIL: ENC[AES256_GCM,data:bjv9KAKSwGYsurjhxkkSOa+a/i5g7n4=,iv:Wao/ymI0t1O/npQFRGLk5cbk75wlWt+8PPsEUPRYjy0=,tag:SaJBI+xx8qOOcF/4tSjDYQ==,type:str]
    POSTGRES_SUPER_PASSWORD: ENC[AES256_GCM,data:78kmPHKGv1kg/k45dNRgN7kmTJDQix9+xrGM6NIKXuE=,iv:kOTBpTT53gefeg0BDpGHLNtP8NcFn0TVG861uftQ2sI=,tag:GzMF37zdc43Cj8rSbTHM9g==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:vW12C1CdVsmHvEkua1S0hmSqaB4m3j4k+WPGhp1GbGDlAxI0WY3u5LoHOAJAosfT9a7Xgmu7fcDryC3193Jzmg==,iv:SfB9y/lO0f1UtmsTwQfVxlXPRueBuHCCfZh+vMUC8c0=,tag:LZpk1tUXZlw7weq+XStRIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eUZ5OW1KU0dEVTExSFc3
            UUY4VHI4c2F5WVBxYWNoYjR1QktwOG9wOTE0CmRoeUhReXE3QWViK0JMSmV3dnZj
            TUthcXBoUUMxZnhmT2o1TWFKN2UzdW8KLS0tIC9KWUxJd21OYS9mWng2UHZWdkE1
            OHhtaHlQNEw3SjJqS29EMmx3aDBmcEUKp8oZgc6uwrYHIFPOM46TEhusHBV1v2pZ
            yhru2UX5CTbFrW80UJTxnFGKqO2TYq8HTbsZrRKa4wYye3v2VkJPWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T16:03:25Z"
    mac: ENC[AES256_GCM,data:zUmL182l9sgU/IFUI+M6loh/1PoZWqZCrsGADd7TUFifh9CkJPTAeOXUpIgyP6+ToBh66kZGYlYPRrEY449ifqZ8BC0u0qf/JNTKtnlLHxq+DwIWyao8Le/gy8KQUKPXYZq1Uv4YHsInY86JHZrnGwNgCWivfxKdKqIA+QGlxM0=,iv:nmfw/DMRJj4OsGxzfyTqdZO8YbyUMMoRYbcx3UPGUV4=,tag:Q9E8c8C1M0eQcdsk261IOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
