# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:ZCTeQLl/6wDfAHM=,iv:DJlWo75IQn9mhblW/WKBnye3vC82SoVeuKQCZUyyhS0=,tag:izU03iyIUp1KeqC0s/v3Ng==,type:str]
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:L1Ys/kfKHRjS9KasqiXg+feoFvc=,iv:Mjy3NIWsxslXpqXSDAuAekfBeHshuCv4hDCOnjDBz1U=,tag:8vqGpyBLKgOmkCSEBtYhKA==,type:str]
    MEDIA_PUBLIC_DOMAIN: ENC[AES256_GCM,data:sCE5+h5gEiVVIUp37uY=,iv:gWEV2zswJrm/tB70NhBxCkN+sKoOZuZoicaG/Fmr434=,tag:CR5ag+TibqjxQ0fWVls6Lg==,type:str]
    MEDIA_PRIVATE_DOMAIN: ENC[AES256_GCM,data:tCKswrv4CsqIJd6QAsSY88o=,iv:evcBwMsHtAZt2ZzyL2GyOJzvFS7/PGY8CHaIE1DADzo=,tag:icdI++bAdEdRUm2zqGxx8g==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fVAeJ2GS1vEnW1B4Gh/U4Cdyx61N0dI=,iv:GjzRJ0cmENrsVey5KZELH9Ffv4SIK2hHGvKc6u3aAd0=,tag:Gq99VZblPy6m4BTbWbjdrA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/5jxTcHUUPWtWQt2eHh3YJY/SuGFo2bAQuOd6SDjmA2se5j7,iv:oWH7IP0WcxqmGaIPu1ybDQECCdCk9Rv0w98hKa8D2YE=,tag:akwzB7LDR85FZQvq2EB80w==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:eY2MJS/cfkztrc1Bo4M7QoQsdPJd5E09quTQvA==,iv:+hKCfk2g1JlhPZ7iRnFjs43OvLLPWpsXLHv+UMJMT0M=,tag:mdKjBZRQeKVwNmb5I13uAg==,type:str]
    NOTIFY_EMAIL: ENC[AES256_GCM,data:fIBwXEzbXdynKyeFurkW/JFlYmMdlmE=,iv:cSFoR2/mllI8O44qkzQek7pDpqSwmNCqSy2maWO751w=,tag:nnCNulBe0Q8Nw85gNhIw3g==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:7OkSrtOvjFDuCCWvAnThwAHlWWyNVpTJGg6RGc+s,iv:x/6Ubwk++qtRbyNeMvf8RtTHDt2ztEE/nI5K1ozxfbA=,tag:bFCmKcAiCqOCOGv8tnWr3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa2haenNQMk11cEVJRTZs
            Q24yN2E2Qm5pTDFjTmdaUUlBM2xyeVhSa3pNClE5MVBHTEdpWjFSVkUvSWczREov
            OU9NK1FQYzdxQUN1a3doMk9MWXBzd2cKLS0tIEQvYy85Zk9STzQvTHl0UzRXekFL
            Mi9BOFBDNVVDNDBPV0krMmlYZ3FLTmsKsndR2e/SxROn8Gt2UPJLc9Lb7mEROdOx
            8XosyV1Sky6ytiyXenrT5Dp3f0FuxWqRvWJvchR9dUX69T3H/9hkNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T15:38:24Z"
    mac: ENC[AES256_GCM,data:z/sv79Z+afURDkv0PSWIkoMUsFKyB2fL+Dix0cF2Vl8Wb5IRQBhq9xLdaSzKtV5eKWU07rQAdVEWVBzr8NjieSx+xAPfOrN3iJ3QYEszmzntVhBZ6yv4cjn2gMh8kq+FzhEC7CihDCn775zuwWDR0AUrH7vGd3ZROYJ0N/uERPU=,iv:Tbb3/WV1fk1d4jqeIPYadz1CYusHITAjqq23AhGNilM=,tag:RrdUE7LNP1EP8Mmst0jSrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
