# https://github.com/Yooooomi/your_spotify#using-docker-compose
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spotify-stats
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/yooooomi/your_spotify_client
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      API_ENDPOINT: "https://spotify-server.${PUBLIC_DOMAIN}"
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: spotify
        hosts:
          - host: &host "spotify.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spotify-stats-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: spotify-stats-mongo
      namespace: default
  values:
    image:
      repository: docker.io/yooooomi/your_spotify_server
      tag: latest
    env:
      TIMEZONE: "${TIMEZONE}"
      API_ENDPOINT: "https://spotify-server.${PUBLIC_DOMAIN}"
      CLIENT_ENDPOINT: "https://spotify.${PUBLIC_DOMAIN}"
      CORS: "https://spotify.${PUBLIC_DOMAIN}"
      # https://github.com/Yooooomi/your_spotify#creating-the-spotify-application
      SPOTIFY_PUBLIC:
        valueFrom:
          secretKeyRef:
            name: spotify-stats
            key: SPOTIFY_CLIENT_ID
      SPOTIFY_SECRET:
        valueFrom:
          secretKeyRef:
            name: spotify-stats
            key: SPOTIFY_CLIENT_SECRET
      MONGO_ENDPOINT:
        valueFrom:
          secretKeyRef:
            name: spotify-stats
            key: MONGO_CONNECTION
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "spotify-server.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spotify-stats-mongo
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: docker.io/library/mongo
      tag: latest
    env:
      MONGO_INITDB_ROOT_USERNAME:
        valueFrom:
          secretKeyRef:
            name: spotify-stats
            key: MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: spotify-stats
            key: MONGO_PASSWORD
    persistence:
      data:
        enabled: true
        path: /data/db
        existingClaim: appdata
        subPath: spotify-stats_mongo
    service:
      main:
        ports:
          http:
            port: 27017
