---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app maddy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ghcr.io/foxcpp/maddy
      tag: 0.6.2
    env:
      DEBUG: "true"
      SMTP_DOMAIN: "${SMTP_DOMAIN}"
      SMTP_SERVER: "${SMTP_HOST}"
      SMTP_USERNAME: "${SMTP_USER}"
      SMTP_PORT: "587"
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${METALLB_MADDY_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 2525
          metrics:
            enabled: false
            port: 9749
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: maddy.conf
        mountPath: /data/maddy.conf
        readOnly: true
      data:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        mountPath: /dev/shm
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app
    # resources:
    #   requests:
    #     cpu: 10m
    #     memory: 10Mi
    #   limits:
    #     memory: 50Mi
