apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:0eBRdv0krTVw5QH6Qb6r/Dla3V/NqQjQgoeVZzfxqQS4rRHuMRUhig==,iv:Z6M94hSQyo1o/NbiChXvSa4XER9qJg2/mY3BpTSBBLo=,tag:4tF/a66SFicqEn+KBTdLeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RThybFZBSldyU0Mvelp4
            L1BoYlE3NU9SYkdEUWJjc2tSczVOSkRpUVQ4CnhVQlo2Uk5mWDJIaTllbmpLaWhD
            RFgwZzJqN1RZNklGL3pDb1pjdS9yRmMKLS0tIHozd2hVZDIzUkJPMVJuK1hzLzRY
            aHoyYzhPRnhWbGNMNkJCS1VGR2RVc3cKg9am+SIp2Mh9UXfzG/rmqOn+PVEBTC7y
            UdYh1UOca0hoUj+2Y1H9Zmfpo6fM9xC7zD3YCodtgZDfzYH87YM9XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T00:04:22Z"
    mac: ENC[AES256_GCM,data:M0YMtqxsij2dIHWTzcomhw0+UeVM4i/rWIDvwjwYLxjyPEpJgLhhfCXwV9wUdboUHj/CjYK811//1PRDcLCSX3pPznOgSeiGlTXSZFyS76WxfuTPtGDmSrnKKvaeqOgsBAohxhl4stfLl53a+pLd2vU+HBBh4PHrsFQLvtgR5sQ=,iv:0SbyKQi9v4FJPkInPP1L7TDojA4jTvdE3iuVsnLhBn8=,tag:W9GUJLssDWUV9ZkS7HYjVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
