# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: healthchecks-secret
stringData:
    SUPERUSER_EMAIL: ENC[AES256_GCM,data:e01d2uC49t+ScdgE2PuhrErcW2Q=,iv:3ISI8YDsu8flBK9a64WpSzfrCO9pWzFDDHsxvH5Ij0g=,tag:gvlf+ulCZr5OJ8Od/mEG5Q==,type:str]
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:4ZjQoTkPUw/xUSoSM6+JoPybCGHspv6TzkolCwLiBA==,iv:ZuLkVg2+aUn9GCAjRmCJd8yLgPeS6DV6WSXk/984Ljs=,tag:pzVKCbjVElm7JURBd+Hnew==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:Z+uzK0jsRa9yqhPFvDXtq6HTLKfw5kWrINFlDu/OPwLi3KlGFRooJfvRP5PhNtMOjoskBxLrxy49NXOcY6aNoqajLQfYQigUHEGLWGZELQ5O8yzUmN5vFkJUXVcGXaLfAE9U6MYeGa4asn4opeFuJLP0yzG/VOjJu+Z2sr4FEhQ=,iv:0F4APLoXqLJcxVSDO8dAu8rMLV6vQpzpCN47VF8blnk=,tag:2kWOQk5136zF9QKKRT0oHA==,type:str]
    DB_USER: ENC[AES256_GCM,data:zeWjD0taTPaKqDAU,iv:ws5u0Ofp85m/H9K6VYg1LQqQ1kD/mL2T7MNubmd9RH4=,tag:YypW4EQ5uaxlFbzpBXb8ZA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:oRQac7iO/Qzq8XfSSrUtrhcXCzvixUS/AvhZwBjSd3X38pxxEeGmwjQ/LUKJMWwlmFx5nTQLtkaxbcEr2NwJMw==,iv:6xbk2j+6bhpWF4MA8/bPI6XMDawgxd256NXC2Z3r/FE=,tag:B2ajYiy1d0FfMhLqhGrq3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYllzZy9DK0FXMTNjTlFR
            QUtjREFGVUtOY2ZXaEJaRDN4TFpENkwzSTB3Cmo3WFdHRXdwTy9qcnZMWEduYjRT
            MVZpN0lSS0RianVkcmtnVjJxZVExbHMKLS0tIGxJcXJtUHZrMnBGNjI2ay95ZTU0
            TUJ2ejFiSGFtTVlnSE5ta1FBT0EzdEEKGrAoqOFTh+aLzHldljy+UO8m9WwGetEj
            Js8uxPgKIjgXG0u11IOy90tfohRbIl+Gz2UWtBzePk6tZZKqtohtRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T20:24:14Z"
    mac: ENC[AES256_GCM,data:+5f84/FgyhIz8I0XlUNzOaXVVhwEkOuDSBT3ldSjAFp4Bvv01JISI/MrlF/cw4S4Ei0UZluK1Osg+w67mxxHnMEdE1FtEclQeDzLzEOTYFIKbywusI3gMY8IOX5D+4bUXybpMmpupGEe8ZBRFdclOO43Ih2DQG23eyIkP4yshNs=,iv:s9UMXc0ptc20Umtw27z6LScnhqfQ5XMKehMJU8f6vwQ=,tag:5fWLbTgTVTK9Li4uTN7Lig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
