# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: minio-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:fQx0EMI=,iv:vpY4IXobFCbgeoszLc6vjmlF6ocXr4SZqys92+Irbqo=,tag:mY7LcFDu7Lw8xPZj1AAtrg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:OQsHdyM4Lxpjjn5M9Ckry1kJ8BdxtLsD0tn9gpvlVIU=,iv:0qLMz7OFrMLZhPuC5DAojN4KCrAyBWpCBVbFiUcThKo=,tag:B8VfX/VIonyYl6uzBrfTrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQVZQbG5BNnhaL3pGNnN0
            TlFzTkM1ZFdQMVZZcU1xdzVmc3kzMzlyTFh3CkZlcFZvUWtDc2VNOGNUcGw0ajRO
            T3pMQ2hiYWRKQ0F6SXFaNXdtd2Jma0kKLS0tIHhEOHRGTFhPN2Z2WkZBZE9yODVx
            cDB5UXluaGM5N21QK3lxSjBxM2w4UzQKHHBJiu9lyjquAlTqxUdJKpx/I1mfCSdJ
            SasUl+jfy66EOKP1um4xVj6EzHhRDRXT2+Zgb160w/ECbIr8f78Oag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T21:31:58Z"
    mac: ENC[AES256_GCM,data:wzGYYq0a0WSaiu933bumtniHn5iWCSkJW5IJ4Qd47cY5PHeGgKGEi7KbcPsHgBlFhZltOBXP8WBzmuj+APUdnWaaNSHnP0E3YR5FURSxKDBxpTECrWlMq83PMiyonfhYPtCqcY+Kly8aH7OCtUeO/ehkzKWB2cuuIIgiL2nKR4g=,iv:HvK2/a83mwmzIPtPp/jrGnfvNqmlTBMpzCG8rtcDez4=,tag:l5MeyegXvZats3btE1GyKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
