# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: maddy
stringData:
    SMTP_REMOTE_USER: ENC[AES256_GCM,data:6fBLIVSjVCSz7kXyTokHnO1Lkkp52IPk,iv:7qYhh0IzgsuyN+OsAblMX8GtF5IbaRlMoUXWvr5Okz4=,tag:w6bq2fsOuWVXzpM5jdKH0g==,type:str]
    SMTP_REMOTE_PASSWORD: ENC[AES256_GCM,data:rPfCqZwNO6EWuhKrG46kN2h8zQ==,iv:QOWHVrQkjBoE/KKMUviY8GfiIyiQ9txsLZqu7TLFILI=,tag:MDJl8r/HIqwXGLW12EH75g==,type:str]
    SMTP_REMOTE_HOST: ENC[AES256_GCM,data:oHoSK6MNw4odqixonRf4HA==,iv:Qyu0ABN3aurPKoJjrNot0jI65iPspcnigZSwRYo99oQ=,tag:vdhJP4fDxdvpWxTpW0449g==,type:str]
    SMTP_REMOTE_DOMAIN: ENC[AES256_GCM,data:h03n2n+XpS+ucg==,iv:G0CvuMNnTrn2q0/Xyg6mxvu8FrCpSQuPS/XkkZG14ZU=,tag:kA9YaO6iNV1fAEhyH6nDLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148wprsnqjq8jughvywnzmvs8gffhrkendpr7g60q8u4rdsj4jvuqk7ltrs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcDhnTFZzY2Zta1Z0ZWRu
            RHliNGxIbkdaWFNsYVFZR1NLRjk3Sk4wcHkwCndEbXI5cEtwZU9mMkR1eGJLV0ZB
            NGFCU0JVWTlJaG9aeVRLcWlVeUlMN1EKLS0tIHBTZ25lTTlUMHpFeUc0b0J4MUpr
            ZXBoaXE3RzVzSjJTSStiLzMwSmRMTVkK6BggrobMVo2ohkCn1Cp9vRpydPDqV6+V
            OIy7o++cpbhBhm4FzJS268SE8f9A2aktyHC993HuHa0u7pdb+NUHAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T04:52:52Z"
    mac: ENC[AES256_GCM,data:lzLVEx1UdNWnGtP7UB9VWt/XAksc6my4k/UmJcgu7vlz5z2C85ziPhqhn2W1U3GfLmDFSkViD1pVgdvwKlNRtCynF3B0VtWpQM+doSNeyx+s5aDv1nzyWigNgbYh+8hWnX5B7/Av7zVQI5j+4H360gXO2Z7RGbElYZHkDSoTCIs=,iv:3Lm8BXaGbq5vylTnWDljVigS5gO5842v6hJuqG1syik=,tag:SHwp5VLnSAE6ZHZj++rCMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
